openapi: 3.0.3
info:
  title: comanda-api-interna
  version: 0.1.0
servers:
- url: ""
tags:
- description: "Contracte per a la gestió CRUD de tasques a Comanda. Les peticions\
    \ rebudes per aquest servei es processaran asíncronament, de manera que en cap\
    \ cas es rebrà una resposta amb el resultat de l'operació com a resposta de les\
    \ peticions."
  name: APP → COMANDA / Tasques
paths:
  /v1/tasques:
    get:
      description: "Obté un llistat paginat de tasques amb possibilitat d'aplicar\
        \ filtres ràpids, filtres avançats, consultes predefinides i perspectives."
      operationId: obtenirLlistatTasques
      parameters:
      - description: Filtre ràpid
        explode: true
        in: query
        name: quickFilter
        required: false
        schema:
          type: string
        style: form
      - description: Filtre avançat en format JSON o expressió del MS
        explode: true
        in: query
        name: filter
        required: false
        schema:
          type: string
        style: form
      - description: Consultes predefinides
        explode: true
        in: query
        name: namedQueries
        required: false
        schema:
          items:
            type: string
          type: array
        style: form
      - description: Perspectives de camp
        explode: true
        in: query
        name: perspectives
        required: false
        schema:
          items:
            type: string
          type: array
        style: form
      - description: Número de pàgina
        explode: true
        in: query
        name: page
        required: false
        schema:
          type: string
        style: form
      - description: Mida de pàgina
        explode: true
        in: query
        name: size
        required: false
        schema:
          format: int32
          type: integer
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TascaPage"
          description: successful operation
      summary: Consulta de tasques
      tags:
      - APP → COMANDA / Tasques
      x-operation-name: obtenirLlistatTasques
      x-accepts:
      - application/json
    post:
      description: Afegeix un missatge d'alta de tasca a una cua de events per a que
        es crei aquesta de forma asíncrona a Comanda.
      operationId: crearTasca
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Tasca"
      responses:
        "200":
          content:
            text/plain:
              schema:
                type: string
          description: successful operation
      summary: Creació s'una tasca
      tags:
      - APP → COMANDA / Tasques
      x-operation-name: crearTasca
      x-content-type: application/json
      x-accepts:
      - text/plain
  /v1/tasques/multiple:
    post:
      description: Afegeix múltiples missatges d'alta de tasques a una cua de events
        per a que es creïn aquestes de forma asíncrona a Comanda.
      operationId: crearMultiplesTasques
      requestBody:
        content:
          application/json:
            schema:
              items:
                $ref: "#/components/schemas/Tasca"
              type: array
      responses:
        "200":
          content:
            text/plain:
              schema:
                type: string
          description: successful operation
      summary: Creació de múltiples tasques
      tags:
      - APP → COMANDA / Tasques
      x-operation-name: crearMultiplesTasques
      x-content-type: application/json
      x-accepts:
      - text/plain
    put:
      description: "Es comprova si les tasques existeixen, i en cas afirmatiu, s'afegeixen\
        \ múltiples missatges de modificació de tasques a una cua de events per a\
        \ que es modifiquin aquestes de forma asíncrona a Comanda. Les tasques no\
        \ existents s'ignoren."
      operationId: modificarMultiplesTasques
      requestBody:
        content:
          application/json:
            schema:
              items:
                $ref: "#/components/schemas/Tasca"
              type: array
      responses:
        "200":
          content:
            text/plain:
              schema:
                type: string
          description: successful operation
      summary: Modificació de múltiples tasques
      tags:
      - APP → COMANDA / Tasques
      x-operation-name: modificarMultiplesTasques
      x-content-type: application/json
      x-accepts:
      - text/plain
  /v1/tasques/{identificador}:
    get:
      description: "Obté les dades d'una tasca identificada pel seu identificador,\
        \ codi d'aplicació i codi d'entorn."
      operationId: consultarTasca
      parameters:
      - description: Identificador de la tasca
        explode: false
        in: path
        name: identificador
        required: true
        schema:
          type: string
        style: simple
      - description: Codi de l'aplicació
        explode: true
        in: query
        name: appCodi
        required: true
        schema:
          type: string
        style: form
      - description: Codi de l'entorn
        explode: true
        in: query
        name: entornCodi
        required: true
        schema:
          type: string
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Tasca"
          description: successful operation
      summary: Consulta d'una tasca
      tags:
      - APP → COMANDA / Tasques
      x-operation-name: consultarTasca
      x-accepts:
      - application/json
    put:
      description: "Es comprova si la tasca existeix, i en cas afirmatiu, s'afegeix\
        \ un missatge de modificació de tasca a una cua de events per a que es modifiqui\
        \ aquesta de forma asíncrona a Comanda."
      operationId: modificarTasca
      parameters:
      - description: Identificador de la tasca
        explode: false
        in: path
        name: identificador
        required: true
        schema:
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Tasca"
      responses:
        "200":
          content:
            text/plain:
              schema:
                type: string
          description: successful operation
      summary: Modificació una tasca
      tags:
      - APP → COMANDA / Tasques
      x-operation-name: modificarTasca
      x-content-type: application/json
      x-accepts:
      - text/plain
components:
  schemas:
    InetAddress:
      example:
        canonicalHostName: canonicalHostName
        holder:
          originalHostName: originalHostName
          hostName: hostName
          address: 6
          family: 1
      properties:
        holder:
          $ref: "#/components/schemas/InetAddressHolder"
        canonicalHostName:
          type: string
      type: object
    InetAddressHolder:
      example:
        originalHostName: originalHostName
        hostName: hostName
        address: 6
        family: 1
      properties:
        originalHostName:
          type: string
        hostName:
          type: string
        address:
          format: int32
          type: integer
        family:
          format: int32
          type: integer
      type: object
    Link:
      example:
        rel: rel
        href: href
      properties:
        rel:
          type: string
        href:
          type: string
      type: object
    PageMetadata:
      example:
        number: 7
        size: 9
        totalPages: 2
        totalElements: 3
      properties:
        number:
          format: int64
          type: integer
        size:
          format: int64
          type: integer
        totalElements:
          format: int64
          type: integer
        totalPages:
          format: int64
          type: integer
      type: object
    Prioritat:
      description: Nivell de prioritat d'una tasca
      enum:
      - NONE
      - BAIXA
      - NORMAL
      - ALTA
      - MAXIMA
      type: string
    Tasca:
      description: Representa una tasca publicada a COMANDA perquè sigui processada
        asíncronament
      example:
        dataCaducitat: 2025-12-01T00:00:00Z
        estatDescripcio: En cua
        responsable: usr1234
        entornCodi: DEV
        descripcio: Generar l'informe mensual de consums per unitat
        tipus: GENERAR_INFORME
        nom: Generar informe mensual
        prioritat: NONE
        redireccio:
          userInfo: userInfo
          handler: null
          query: query
          path: path
          protocol: protocol
          ref: ref
          file: file
          port: 0
          hashCode: 5
          authority: authority
          host: host
          hostAddress:
            canonicalHostName: canonicalHostName
            holder:
              originalHostName: originalHostName
              hostName: hostName
              address: 6
              family: 1
          tempState:
            protocol: protocol
            ref: ref
            file: file
            port: 5
            hashCode: 2
            authority: authority
            host: host
        usuarisAmbPermis: "[\"usr1\", \"usr2\"]"
        grup: GESTORS
        appCodi: PORTAFIB
        numeroExpedient: EXP-12345/2025
        estat: PENDENT
        dataFi: 2025-11-20T10:00:00Z
        dataInici: 2025-11-20T09:30:00Z
        grupsAmbPermis: "[\"GESTORS\", \"SUPORT\"]"
        identificador: TAS-2025-0001
      properties:
        appCodi:
          description: Codi de l'aplicació que publica la tasca
          example: PORTAFIB
          type: string
        entornCodi:
          description: Codi de l'entorn de l'aplicació
          example: DEV
          type: string
        identificador:
          description: Identificador únic de la tasca en l'àmbit de l'APP
          example: TAS-2025-0001
          type: string
        tipus:
          description: Tipus funcional de la tasca
          example: GENERAR_INFORME
          type: string
        nom:
          description: Nom curt de la tasca
          example: Generar informe mensual
          type: string
        descripcio:
          description: Descripció detallada de la tasca
          example: Generar l'informe mensual de consums per unitat
          type: string
        estat:
          $ref: "#/components/schemas/TascaEstat"
        estatDescripcio:
          description: Descripció de l'estat actual
          example: En cua
          type: string
        numeroExpedient:
          description: Número d'expedient relacionat (si aplica)
          example: EXP-12345/2025
          type: string
        prioritat:
          $ref: "#/components/schemas/Prioritat"
        dataInici:
          description: Data d'inici prevista o real
          example: 2025-11-20T09:30:00Z
          format: date-time
          type: string
        dataFi:
          description: Data de finalització
          example: 2025-11-20T10:00:00Z
          format: date-time
          type: string
        dataCaducitat:
          description: Data de caducitat límit
          example: 2025-12-01T00:00:00Z
          format: date-time
          type: string
        redireccio:
          $ref: "#/components/schemas/URL"
        responsable:
          description: Usuari responsable
          example: usr1234
          type: string
        grup:
          description: Grup responsable
          example: GESTORS
          type: string
        usuarisAmbPermis:
          description: Llista d'usuaris amb permís
          example: "[\"usr1\", \"usr2\"]"
          items:
            type: string
          type: array
        grupsAmbPermis:
          description: Llista de grups amb permís
          example: "[\"GESTORS\", \"SUPORT\"]"
          items:
            type: string
          type: array
      type: object
    TascaEstat:
      description: Estat de processament d'una tasca
      enum:
      - PENDENT
      - INICIADA
      - FINALITZADA
      - CANCELADA
      - ERROR
      type: string
    TascaPage:
      example:
        links:
        - rel: rel
          href: href
        - rel: rel
          href: href
        page:
          number: 7
          size: 9
          totalPages: 2
          totalElements: 3
        content:
        - dataCaducitat: 2025-12-01T00:00:00Z
          estatDescripcio: En cua
          responsable: usr1234
          entornCodi: DEV
          descripcio: Generar l'informe mensual de consums per unitat
          tipus: GENERAR_INFORME
          nom: Generar informe mensual
          prioritat: NONE
          redireccio:
            userInfo: userInfo
            handler: null
            query: query
            path: path
            protocol: protocol
            ref: ref
            file: file
            port: 0
            hashCode: 5
            authority: authority
            host: host
            hostAddress:
              canonicalHostName: canonicalHostName
              holder:
                originalHostName: originalHostName
                hostName: hostName
                address: 6
                family: 1
            tempState:
              protocol: protocol
              ref: ref
              file: file
              port: 5
              hashCode: 2
              authority: authority
              host: host
          usuarisAmbPermis: "[\"usr1\", \"usr2\"]"
          grup: GESTORS
          appCodi: PORTAFIB
          numeroExpedient: EXP-12345/2025
          estat: PENDENT
          dataFi: 2025-11-20T10:00:00Z
          dataInici: 2025-11-20T09:30:00Z
          grupsAmbPermis: "[\"GESTORS\", \"SUPORT\"]"
          identificador: TAS-2025-0001
        - dataCaducitat: 2025-12-01T00:00:00Z
          estatDescripcio: En cua
          responsable: usr1234
          entornCodi: DEV
          descripcio: Generar l'informe mensual de consums per unitat
          tipus: GENERAR_INFORME
          nom: Generar informe mensual
          prioritat: NONE
          redireccio:
            userInfo: userInfo
            handler: null
            query: query
            path: path
            protocol: protocol
            ref: ref
            file: file
            port: 0
            hashCode: 5
            authority: authority
            host: host
            hostAddress:
              canonicalHostName: canonicalHostName
              holder:
                originalHostName: originalHostName
                hostName: hostName
                address: 6
                family: 1
            tempState:
              protocol: protocol
              ref: ref
              file: file
              port: 5
              hashCode: 2
              authority: authority
              host: host
          usuarisAmbPermis: "[\"usr1\", \"usr2\"]"
          grup: GESTORS
          appCodi: PORTAFIB
          numeroExpedient: EXP-12345/2025
          estat: PENDENT
          dataFi: 2025-11-20T10:00:00Z
          dataInici: 2025-11-20T09:30:00Z
          grupsAmbPermis: "[\"GESTORS\", \"SUPORT\"]"
          identificador: TAS-2025-0001
      properties:
        content:
          description: Contingut de la pàgina
          items:
            $ref: "#/components/schemas/Tasca"
          type: array
        page:
          $ref: "#/components/schemas/PageMetadata"
        links:
          description: Enllaços HATEOAS
          items:
            $ref: "#/components/schemas/Link"
          type: array
      type: object
    URL:
      example:
        userInfo: userInfo
        handler: null
        query: query
        path: path
        protocol: protocol
        ref: ref
        file: file
        port: 0
        hashCode: 5
        authority: authority
        host: host
        hostAddress:
          canonicalHostName: canonicalHostName
          holder:
            originalHostName: originalHostName
            hostName: hostName
            address: 6
            family: 1
        tempState:
          protocol: protocol
          ref: ref
          file: file
          port: 5
          hashCode: 2
          authority: authority
          host: host
      properties:
        protocol:
          type: string
        host:
          type: string
        port:
          format: int32
          type: integer
        file:
          type: string
        query:
          type: string
        authority:
          type: string
        path:
          type: string
        userInfo:
          type: string
        ref:
          type: string
        hostAddress:
          $ref: "#/components/schemas/InetAddress"
        handler:
          $ref: "#/components/schemas/URLStreamHandler"
        hashCode:
          format: int32
          type: integer
        tempState:
          $ref: "#/components/schemas/UrlDeserializedState"
      type: object
    URLStreamHandler:
      type: object
    UrlDeserializedState:
      example:
        protocol: protocol
        ref: ref
        file: file
        port: 5
        hashCode: 2
        authority: authority
        host: host
      properties:
        protocol:
          type: string
        host:
          type: string
        port:
          format: int32
          type: integer
        authority:
          type: string
        file:
          type: string
        ref:
          type: string
        hashCode:
          format: int32
          type: integer
      type: object

